name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "mail"
database_id = "8a60bc6e-fbcc-4bb5-8fd1-0f031198ad5a"

[[kv_namespaces]]
binding = "kv"
id = "a1c1ecba23e243edaf9939c3de33530a"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]
